spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/test_2?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: